{% set version = "0.6.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mosaiccalc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mosaicCalc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mosaicCalc/mosaicCalc_{{ version }}.tar.gz
  sha256: 399c280824d0c29b39cb1e01ebb9af28397a470b7199f160898acb23b57403bb

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-deriv
    - r-mass
    - r-matrix
    - r-ryacas
    - r-calculus
    - r-dplyr
    - r-ggformula
    - r-ggplot2
    - r-glue
    - r-metr >=0.11.0
    - r-calculus
    - r-mosaic
    - r-mosaiccore >=0.9.2
    - r-orthopolynom
    - r-rlang
    - r-sp
    - r-tibble
  run:
    - r-base
    - r-deriv
    - r-mass
    - r-matrix
    - r-ryacas
    - r-calculus
    - r-dplyr
    - r-ggformula
    - r-ggplot2
    - r-glue
    - r-metr >=0.11.0
    - r-calculus
    - r-mosaic
    - r-mosaiccore >=0.9.2
    - r-orthopolynom
    - r-rlang
    - r-sp
    - r-tibble

test:
  commands:
    - $R -e "library('mosaicCalc')"           # [not win]
    - "\"%R%\" -e \"library('mosaicCalc')\""  # [win]

about:
  home: https://github.com/ProjectMOSAIC/mosaicCalc
  license: GPL-2.0-or-later
  summary: Software to support the introductory *MOSAIC Calculus* textbook <https://www.mosaic-web.org/MOSAIC-Calculus/>), one of many data- and modeling-oriented educational resources developed by Project MOSAIC (<https://www.mosaic-web.org/>). Provides symbolic and numerical differentiation and integration, as well as
    support for applied linear algebra (for data science), and differential equations/dynamics. Includes grammar-of-graphics-based functions for drawing vector fields, trajectories, etc. The software is suitable for general use, but intended mainly for teaching calculus.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dragz
